// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

// import MobileNavController from "./mobile_nav_controller"
// application.register("mobileNav", MobileNavController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobileMenu", MobileMenuController)

import MobileMarkAsReadController from "./mobile_mark_as_read_controller"
application.register("mobileMarkAsRead", MobileMarkAsReadController)

import DesktopMarkAsReadController from "./desktop_mark_as_read_controller"
application.register("desktopMarkAsRead", DesktopMarkAsReadController)
