// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ViewedEntriesController from "./viewed_entries_controller"
application.register("viewed_entries", ViewedEntriesController)

import BookmarksController from "./bookmarks_controller"
application.register("bookmarks", BookmarksController)

import AlertsController from "./alerts_controller"
application.register("alerts", AlertsController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)
