AllCops:
  NewCops:
    enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/bundle/**/*'

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false