AllCops:
  NewCops:
    enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/bundle/**/*'

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
