development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_DEVELOPMENT_DATABASE'] %>
  pool: 5
  username: <%= ENV['PG_DEVELOPMENT_USERNAME'] %>
  password: <%= ENV['PG_DEVELOPMENT_PASSWORD'] %>
  
test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_TEST_DATABASE'] %>
  pool: 5
  username: <%= ENV['PG_TEST_USERNAME'] %>
  password: <%= ENV['PG_TEST_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_PRODUCTION_DATABASE'] %>
  pool: 5
  username: <%= ENV['PG_PRODUCTION_USERNAME'] %>
  password: <%= ENV['PG_PRODUCTION_PASSWORD'] %>
  