development:
  adapter: postgresql
  encoding: unicode
  database: rssr_development
  pool: 5
  username: <%= ENV['DB_DEV_USERNAME'] %>
  password: <%= ENV['DB_DEV_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: rssr_test
  pool: 5
  username: <%= ENV['DB_TEST_USERNAME'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: rssr_production
  pool: 5
  username: <%= ENV['DB_PROD_USERNAME'] %>
  password: <%= ENV['DB_PROD_PASSWORD'] %>