class ConvertRegexpFilters < ActiveRecord::Migration[7.2]
  def up
    Filter.where(comparison: Filter::MATCHES_FILTER).destroy_all
    
    [
      "wellington phoenix",
      "wellington united",
      "elon",
      "elon musk",
      "dan carter",
      "chrissy teigen",
      "jada pinkett",
      "jake paul",
      "jennifer lopez",
      "joseph parker",
      "kardashian",
      "logan paul",
      "meghan markle",
      "richard osman",
      "richie mccaw",
      "tyson fury",
      "will smith",
      "amber heard",
      "lukaku",
      "black cap",
      "black friday",
      "baseball",
      "basketball",
      "football",
      "softball",
      "prince",
      "princess",
      "kickbox",
      "kickboks",
      "pixel 6",
      "pixel 7",
      "pixel bud",
      "rode duivel",
      "rode kaart",
      "inbraak",
      "inbraken",
      "ingebroken",
      "all blacks",
      "all whites",
      "belisia",
      "chiefs",
      "crusaders",
      "fc",
      "highlanders",
      "kvk",
      "lierse",
      "manchester united",
      "patro",
      "silver fern",
      "six nations",
      "termien",
      "wallabies",
      "warriors",
      "white ferns",
      "broncos",
      "sports",
      "soccer",
      "rugby",
      "nrl",
      "nfl",
      "cricket",
      "afl",
      "voetbal",
    ].each do |value|
      Filter.create(comparison: Filter::INCLUDES_FILTER, value: value)
    end
  end

  def down
  end
end
