name: Ruby on Rails - Install dependencies, run security checks, linters and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-checks-lint-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          bundler-cache: true
      - name: Run security checks
        run: |
          bundle exec bundle-audit --update
          bundle exec brakeman -q -w2
      - name: Run linters
        run: |
          bundle exec rubocop --parallel
      - name: Rub tests
        run: |
          bundle exec rspec spec --format documentation
